version: "3.7"
services:
  bmi-app:
    build: .
    image: bmi-image
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html/
    # environment:
    # depends_on:
    # links:
    # network:
#
# $ docker compose up
# the app will be running at http://localhost:8080/
#
# $ docker compose up --build
# for rebuild on change, will also be running at http://localhost:8080/
#
# docker compose images: This command will list the images you’ve built using the current docker-compose file.
#
# docker compose ps: This command list all the containers in the current docker-compose file. They can then either be running or stopped.
#
# docker compose down
# it stops all the services and cleans up the containers, networks, and images.

#
######## for pushing image to the docker hub ##########
# 1. run the "up" command
# 2. login to docker hub (from terminal)
# 3. create repository on docker hub (in browser)
# 4. run push command (see syntax on docker hub, inside the repository)

######## once image is uploaded on the repo, you can pull it ########
# pull image from the repository on docker hub
# $ docker pull lelekaspb/bmi-application:latest
#
# run
# $ docker run --name bmi-repo-image -p 8080:80 lelekaspb/bmi-application
#
# see that it is running on http://localhost:8080/

